/* Plain-language wording for every check, for website owners.
   problem: what's wrong, in everyday words (shown when the check fails)
   why:     why it matters for the business
   The check's own title/message/fix stay available under "Technical details". */

const E = {
  'tech.https': ['Your website isn\'t secure (no HTTPS).', 'Browsers show "Not secure" to visitors, and Google ranks secure sites higher.'],
  'tech.http-redirect': ['The insecure (http://) version of your site doesn\'t send visitors to the secure one.', 'Visitors and Google can land on an insecure copy, which looks untrustworthy and splits your ranking.'],
  'tech.host-variant': ['Your site behaves differently with and without "www".', 'People who type the other version get an error or a duplicate copy of your site.'],
  'tech.robots-txt': ['Your site is missing a robots.txt file.', 'It\'s the standard file search engines read first; it also tells them where your sitemap is.'],
  'tech.robots-googlebot': ['Your site is blocking Google from reading some pages.', 'Pages Google can\'t read can\'t appear in search results.'],
  'tech.sitemap': ['Google can\'t find a list of your pages (XML sitemap).', 'A sitemap helps Google discover every page, especially new ones, faster.'],
  'tech.sitemap-in-robots': ['Your robots.txt doesn\'t point search engines to your sitemap.', 'It\'s an easy way to make sure every search engine finds your page list.'],
  'tech.sitemap-quality': ['Your sitemap lists pages that are broken, redirected or hidden.', 'Google trusts sitemaps less when they contain pages that shouldn\'t be indexed.'],
  'tech.http-errors': ['Some pages on your site are broken.', 'Visitors hit dead ends and Google drops broken pages from results.'],
  'tech.load-errors': ['Some pages didn\'t load at all.', 'If we couldn\'t load them, visitors and Google may not be able to either.'],
  'tech.broken-internal-links': ['Some of your links lead to pages that don\'t exist.', 'Broken links frustrate visitors and waste Google\'s time crawling your site.'],
  'tech.broken-external-links': ['Some links to other websites are broken.', 'Dead links make your site look neglected.'],
  'tech.redirect-chains': ['Some addresses bounce through several redirects.', 'Each extra hop slows visitors down and weakens the page\'s ranking signals.'],
  'tech.links-to-redirects': ['Some of your links point to old addresses that redirect.', 'Linking straight to the final page is faster and clearer for Google.'],
  'tech.canonical-missing': ['Google may have difficulty working out which version of a page should appear in search results.', 'Without a "preferred address" tag, duplicates of a page can compete with each other.'],
  'tech.canonical-valid': ['Some pages tell Google the wrong "preferred address".', 'Google may show the wrong page — or none — in search results.'],
  'tech.noindex-home': ['Your homepage is hidden from Google.', 'A hidden homepage means your business won\'t show up when people search for it.'],
  'tech.noindex-pages': ['Some pages are set to be hidden from Google.', 'Check this is intentional — hidden pages never appear in search results.'],
  'tech.duplicate-urls': ['The same page is available at more than one address.', 'Duplicates split your ranking strength between copies.'],
  'tech.trailing-slash': ['Some pages open at two slightly different addresses (with and without a "/").', 'Google can treat these as duplicate pages.'],
  'tech.url-structure': ['Some page addresses are long or messy.', 'Short, readable addresses are easier to share and slightly easier for Google to understand.'],
  'tech.viewport': ['Your site isn\'t set up to display properly on phones.', 'Most visitors are on mobile, and Google ranks sites based on their mobile version.'],
  'tech.lang': ['Your pages don\'t say what language they\'re in.', 'It helps Google show your site to the right audience and helps screen readers.'],
  'tech.charset': ['Your pages don\'t declare their text encoding.', 'Without it, special characters can display as gibberish in some browsers.'],
  'tech.favicon': ['Your site has no browser-tab icon (favicon).', 'Google shows it next to your search result — without it you look less established.'],
  'tech.soft-404': ['Pages that don\'t exist don\'t show a proper "not found" error.', 'Google gets confused about which pages are real, and broken links stay hidden.'],
  'tech.mixed-content': ['Some secure pages load insecure files.', 'Browsers may block those files or show security warnings.'],
  'tech.js-content': ['Some pages only show their content after JavaScript runs.', 'Some search engines and social previews can\'t see that content.'],
  'onpage.title-missing': ['Some pages have no title for Google to show.', 'The title is the blue headline in search results — without it Google makes one up.'],
  'onpage.title-length': ['Some page titles are too short or too long.', 'Long titles get cut off in Google; short ones miss the chance to describe the page.'],
  'onpage.title-duplicate': ['Several pages share the same title.', 'Google can\'t tell the pages apart, so they compete with each other.'],
  'onpage.title-quality': ['Some page titles are vague (e.g. "Home").', 'A descriptive title is one of the strongest signals of what a page is about.'],
  'onpage.meta-missing': ['Some pages have no search-result description.', 'The description is your sales pitch under the title in Google — without it Google picks random text.'],
  'onpage.meta-length': ['Some search-result descriptions are too short or too long.', 'Too long gets cut off; too short wastes the chance to win the click.'],
  'onpage.meta-duplicate': ['Several pages share the same search-result description.', 'Repeated descriptions are usually ignored by Google.'],
  'onpage.meta-quality': ['Some search-result descriptions are placeholders or copies of the title.', 'A real summary with a reason to click gets more visitors from Google.'],
  'onpage.h1-missing': ['Some pages have no main heading.', 'The main heading tells visitors and Google what the page is about.'],
  'onpage.h1-multiple': ['Some pages have more than one main heading.', 'One clear main heading per page is easiest for Google to understand.'],
  'onpage.heading-empty': ['Some headings are empty.', 'Empty headings confuse screen readers and add nothing for Google.'],
  'onpage.heading-order': ['Some headings skip levels.', 'A logical heading order helps visitors scan and helps Google understand the structure.'],
  'onpage.subheadings': ['Some longer pages have no subheadings.', 'Subheadings make pages easier to read and help Google understand each section.'],
  'onpage.orphans': ['Some pages aren\'t linked from anywhere on your site.', 'Visitors can\'t find them, and Google treats unlinked pages as unimportant.'],
  'onpage.few-inbound': ['Some pages are hardly linked to from the rest of your site.', 'Internal links tell Google which pages matter most.'],
  'onpage.important-unlinked': ['Your most important pages aren\'t linked from your site.', 'Key pages need links from your homepage or menu to rank well.'],
  'onpage.anchor-text': ['Some links say "click here" or nothing at all.', 'Descriptive link text helps visitors and tells Google what the linked page is about.'],
  'onpage.dead-ends': ['Some pages don\'t link anywhere else.', 'Visitors reach a dead end instead of moving towards contacting you.'],
  'content.thin': ['Some pages have very little text.', 'Google rarely ranks pages with almost no content.'],
  'content.low-word-count': ['Some pages could use more helpful content.', 'Pages that answer customers\' questions in depth tend to rank better.'],
  'content.duplicate': ['Some pages have exactly the same text.', 'Google usually shows only one of the copies — or neither.'],
  'content.near-duplicate': ['Some pages are almost identical.', 'Near-duplicate pages compete with each other instead of ranking for different searches.'],
  'content.keyword-stuffing': ['A word or phrase is repeated unnaturally often.', 'Google can demote pages that look written for search engines rather than people.'],
  'content.readability': ['Some text is hard to read.', 'Visitors leave pages that are hard to read, which hurts enquiries.'],
  'content.semantic-html': ['Your pages don\'t mark out their main sections in the code.', 'Clear structure helps Google and screen readers find the main content.'],
  'images.alt-missing': ['Some images have no description (alt text).', 'Google can\'t see images — alt text tells it what they show, and helps visually impaired visitors.'],
  'images.alt-empty-link': ['Some clickable images have no description.', 'Screen readers and Google can\'t tell where those links go.'],
  'images.alt-quality': ['Some image descriptions are file names or far too long.', 'Short, real descriptions work best for Google Images and accessibility.'],
  'images.broken': ['Some images are missing.', 'Broken images make the site look unfinished.'],
  'images.large': ['Some images are very large files.', 'Large images are the most common reason sites load slowly on phones.'],
  'images.dimensions': ['Some images don\'t reserve their space while loading.', 'The page jumps around as images load, which annoys visitors and Google measures it.'],
  'images.format': ['Some large images could use a modern, smaller format.', 'WebP/AVIF images are typically 25–50% smaller with the same quality.'],
  'images.lazy': ['Image-heavy pages load every image straight away.', 'Loading off-screen images later makes the page appear much faster.'],
  'images.filenames': ['Some image file names are meaningless (e.g. IMG_1234.jpg).', 'Descriptive file names help your images appear in Google Images.'],
  'perf.lighthouse': ['Google\'s speed test scores your mobile site low.', 'Slow sites lose visitors before the page even appears, and speed affects rankings.'],
  'perf.core-web-vitals': ['Real visitors experience slow loading or a jumpy layout.', 'Google uses these real-user measurements as a ranking factor.'],
  'perf.server-response': ['Your server is slow to start sending pages.', 'Every page is delayed before anything appears on screen.'],
  'perf.html-size': ['Some pages\' code is very large.', 'Bloated pages take longer to download, especially on mobile data.'],
  'perf.render-blocking': ['Some scripts stop the page from showing until they load.', 'Visitors stare at a blank screen for longer.'],
  'perf.image-caching': ['Browsers aren\'t told to keep your images.', 'Returning visitors re-download the same images every time.'],
  'local.business-schema': ['Google isn\'t given your business details in a format it understands.', 'Business markup helps you appear in local results and the map.'],
  'local.business-details': ['Your business details for Google are incomplete.', 'Complete details (hours, location, phone) help you rank in "near me" searches.'],
  'local.phone': ['Your phone number isn\'t visible on every page.', 'Visitors ready to call shouldn\'t have to hunt for your number.'],
  'local.click-to-call': ['Your phone number can\'t be tapped to call.', 'On a phone, one tap to call is the fastest way to win the enquiry.'],
  'local.nap-consistency': ['Your phone number differs between your site and your business details.', 'Inconsistent details make Google less confident about your business.'],
  'local.address': ['Your business location isn\'t shown on the site.', 'Customers and Google both use your location to judge if you serve their area.'],
  'local.contact-page': ['There\'s no clear contact page or form.', 'Visitors who are ready to buy need an obvious way to reach you.'],
  'local.map': ['There\'s no Google Maps link or map.', 'A map builds trust and connects your site to your Google Business Profile.'],
  'local.location-keywords': ['Your homepage doesn\'t mention your town or city in its title and main heading.', 'Mentioning where you work helps you show up for local searches.'],
  'local.google-business-profile': ['Google Business Profile isn\'t checked automatically.', 'Your free Google Business Profile drives the map results for local searches.'],
  'schema.jsonld-errors': ['Some of your Google business data has errors.', 'Google ignores the whole block when it contains a mistake.'],
  'schema.homepage': ['Your homepage gives Google no structured information about your business.', 'Structured data helps Google understand who you are and can unlock richer search results.'],
  'schema.organization': ['Google isn\'t given your official business identity.', 'It helps Google show the right name, logo and links for your business.'],
  'schema.required-properties': ['Some rich-result data is missing required details.', 'Without them Google won\'t show extras like FAQs, stars or breadcrumbs.'],
  'schema.article': ['Your article markup is missing recommended details.', 'Complete details help articles appear richer in Google.'],
  'schema.open-graph': ['Links to your pages don\'t show a proper preview on WhatsApp/Facebook.', 'A good preview image and title gets far more clicks when people share your site.'],
  'schema.twitter-card': ['Links shared on X/Twitter show a small preview.', 'A large preview card stands out more in feeds.'],
  'schema.breadcrumbs': ['Deeper pages don\'t show where they sit in your site.', 'Breadcrumbs can appear in Google results and help visitors navigate.'],
  'schema.coverage': ['Some pages have no structured data.', 'Structured data helps Google understand each page.'],
  'sec.hsts': ['Browsers aren\'t told to always use the secure version of your site.', 'It closes a small gap where a first visit could be intercepted.'],
  'sec.headers': ['Some basic security settings are missing.', 'These headers protect visitors against common attacks such as clickjacking.'],
};

export function explain(check) {
  const e = E[check.id];
  return { problem: e?.[0] || check.title, why: e?.[1] || '' };
}
